
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jul  3 2023 05:11:15 EDT (Jul  3 2023 09:11:15 UTC)

// Verification Directory fv/counter 

module counter(clk, rst, q);
  input clk, rst;
  output [3:0] q;
  wire clk, rst;
  wire [3:0] q;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10;
  DFFRHQX2 \q_reg[0] (.RN (n_10), .CK (clk), .D (n_8), .Q (q[0]));
  DFFRHQX2 \q_reg[2] (.RN (n_10), .CK (clk), .D (n_6), .Q (q[2]));
  AOI21X1 g214__2398(.A0 (n_1), .A1 (n_7), .B0 (q[0]), .Y (n_9));
  AOI21X1 g215__5107(.A0 (n_3), .A1 (n_7), .B0 (n_5), .Y (n_8));
  OAI32X1 g217__6260(.A0 (q[0]), .A1 (q[1]), .A2 (n_2), .B0 (n_5), .B1
       (n_7), .Y (n_6));
  MXI2XL g216__4319(.A (n_7), .B (n_0), .S0 (q[0]), .Y (n_4));
  NAND2XL g218__8428(.A (q[0]), .B (n_2), .Y (n_3));
  NAND2BX1 g220__5526(.AN (q[2]), .B (n_5), .Y (n_1));
  NAND2XL g219__6783(.A (q[2]), .B (q[3]), .Y (n_7));
  NAND2XL g221__3680(.A (q[1]), .B (q[2]), .Y (n_0));
  INVXL g223(.A (rst), .Y (n_10));
  DFFRX2 \q_reg[3] (.RN (n_10), .CK (clk), .D (n_9), .Q (q[3]), .QN
       (n_2));
  DFFRX2 \q_reg[1] (.RN (n_10), .CK (clk), .D (n_4), .Q (q[1]), .QN
       (n_5));
endmodule

